import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createTaskService} from '../task-service.js';
import {createTask,submissionPatch,reviewPatch,taskTotals,selectTasks,reportDocument,validDate,MAX_PHOTOS} from '../task-model.js';
import {fakeSdk} from './fake-sdk.mjs';
const phone='03000000001',other='03000000002',base='businesses/noor-traders',image='data:image/jpeg;base64,/9j/2Q==';
const owner={role:'owner',uid:'owner'},staff={role:'staff',uid:'staff',phone};
const assignment={phone,staffName:'Employee <one>',title:'Arrange shelves',details:'Check every row',date:'2026-09-08',maxPoints:10};
const submitted=()=>({...createTask(assignment,owner,'t1'),...submissionPatch(createTask(assignment,owner,'t1'),staff,{photos:[image,image],submissionId:'submission-1',staffNote:'Done',expectedRevision:0})});
const review=(t,points=8)=>reviewPatch(t,owner,{status:'approved',points,submissionId:t.submissionId,expectedRevision:t.revision});

test('task approval awards points once, and corrections require a fresh submission',()=>{
 const t=submitted();assert.equal(taskTotals([t]).points,0);
 const approved={...t,...review(t)};assert.equal(taskTotals([approved]).points,8);
 assert.throws(()=>review(approved),/تصدیق/);
 assert.throws(()=>submissionPatch(approved,staff,{photos:[image],expectedRevision:1,submissionId:'submission-2'}));
 const rejected={...t,...reviewPatch(t,owner,{status:'changes_requested',points:0,ownerNote:'Clean again',expectedRevision:1,submissionId:t.submissionId})};
 const retry={...rejected,...submissionPatch(rejected,staff,{photos:[image],expectedRevision:1,submissionId:'submission-2'})};
 assert.equal(retry.revision,2);assert.equal(taskTotals([retry]).points,0);
 assert.throws(()=>reviewPatch(retry,owner,{status:'approved',points:10,submissionId:t.submissionId,expectedRevision:1}));
 assert.equal(taskTotals([{...retry,...review(retry,10)}]).points,10);
});
test('role, own phone, stale revisions, invalid points and missing evidence are rejected',()=>{
 const t=createTask(assignment,owner,'t1');
 assert.throws(()=>createTask(assignment,staff,'t2'));
 assert.throws(()=>submissionPatch(t,{...staff,phone:other},{photos:[image],expectedRevision:0,submissionId:'submission-1'}));
 for(const photos of [[],Array(MAX_PHOTOS+1).fill(image),['data:text/html;base64,QQ==']])assert.throws(()=>submissionPatch(t,staff,{photos,expectedRevision:0,submissionId:'submission-1'}));
 for(const points of [-1,11,1.5,NaN])assert.throws(()=>review(submitted(),points));
 assert.throws(()=>reviewPatch(submitted(),staff,{status:'approved',points:10}));
 assert.throws(()=>reviewPatch(submitted(),owner,{status:'changes_requested',ownerNote:' ',expectedRevision:1,submissionId:'submission-1'}));
 assert.equal(validDate('2026-02-30'),false);
});
test('PDF reports embed every owner picture, escape user text, and show staff point accounting',()=>{
 const t={...submitted(),...review(submitted()),title:'<script>alert(1)</script>',ownerNote:'OK <img src=x onerror=boom>'};
 const photos=new Map(t.photoIds.map(id=>['t1/'+id,image]));
 const html=reportDocument({tasks:[t],photos,includePhotos:true,attendance:[{date:t.date,phone,checkIn:'09:00',finalScore:10}],salary:{periodLabel:'September 2026',monthlySalary:30000,expectedHours:300,normalMin:600,normalSalary:1000,otMin:60,overtimeAmount:100,attPoints:10,taskPoints:8,points:18,pointsAmount:180,bonus:500,advance:200,final:1580}});
 assert.equal((html.match(/<img src="data:image/g)||[]).length,2);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('مجموعہ: 18'));
 assert.ok(html.includes('Salary / تنخواہ'));assert.ok(html.includes('Rs 1,580'));
 const staffHtml=reportDocument({tasks:[t]});assert.ok(staffHtml.includes('ٹاسک پوائنٹس: 8'));assert.ok(!staffHtml.includes('data:image'));
 assert.throws(()=>reportDocument({tasks:[t],includePhotos:true,photos:new Map()}),/تصاویر/);
 assert.equal(selectTasks([t],{phone:other}).length,0);assert.equal(selectTasks([t],{from:'2026-09-09'}).length,0);
 assert.throws(()=>selectTasks([t],{from:'2026-09-09',to:'2026-09-08'}));
});
test('actual service assigns, atomically submits 8 photos, reviews, and migrates profile ownership',async()=>{
 const f=fakeSdk({initialUser:{uid:'owner',isAnonymous:false,email:'hp6235@gmail.com'}});let currentPhone='';
 f.records.set(base+'/staffAccounts/'+phone,{phone,name:'Employee',active:true,loginEnabled:true});
 const service=createTaskService({fs:{},auth:f.auth,sdk:f.sdk,getStaffPhone:()=>currentPhone});
 const id=await service.assign(assignment),path=base+'/staffTasks/'+id;
 f.changeUser({uid:'staff',isAnonymous:true});currentPhone=phone;
 f.failNextCommit();await assert.rejects(()=>service.submit(id,{photos:[image,image],submissionId:'submission-failed',expectedRevision:0}));
 assert.equal(f.records.get(path).status,'assigned');assert.equal([...f.records.keys()].filter(k=>k.includes('/taskPhotos/')).length,0);
 await service.submit(id,{photos:Array(MAX_PHOTOS).fill(image),submissionId:'submission-okay',expectedRevision:0});
 assert.equal((await service.photos({...f.records.get(path),id})).size,MAX_PHOTOS);
 const rows=[];const unsub=service.listen(list=>rows.push(list),assert.fail);await Promise.resolve();assert.equal(rows.at(-1).length,1);unsub();
 currentPhone=other;
 await assert.rejects(()=>service.submit(id,{photos:[image],expectedRevision:1,submissionId:'submission-bad'}));
 f.changeUser({uid:'owner',isAnonymous:false,email:'hp6235@gmail.com'});currentPhone='';
 const decision={status:'approved',points:7,ownerNote:'Checked all images',expectedRevision:1,submissionId:'submission-okay'};
 const outcomes=await Promise.allSettled([service.review(id,decision),service.review(id,decision)]);
 assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(taskTotals([f.records.get(path)]).points,7);
 await service.migratePhone(phone,other,'Renamed employee');assert.equal(f.records.get(path).phone,other);assert.equal((await service.photos({...f.records.get(path),id})).size,MAX_PHOTOS);
});
